services:
  - type: web
    name: tron-wallet-app
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
